### ISSUE TITLE
Weight consecutive repeats slightly heavier than other repeats

### ISSUE THREAD

**Issue by spherulitic** [jvc56/tournament_pairing_algorithms#1]
Playing the same player two rounds in a row is less desirable than playing a repeat of a player from earlier in the tournament. 

Here it appears that the pairing Wittman / Huneault and Aitken / Farini is basically the same, but avoids the back-to-back repeat.

![Screenshot from 2023-05-21 15-01-29](https://github.com/jvc56/tournament_pairing_algorithms/assets/8773017/45224d1c-6f54-4cd0-a230-d4cf1db4c065)
![Screenshot from 2023-05-21 14-58-39](https://github.com/jvc56/tournament_pairing_algorithms/assets/8773017/5729fb2f-ac35-4896-9748-ec95ad8ab503)
[Sun_May_21_14_54_10_2023_B_round_14_based_on_12.log](https://github.com/jvc56/tournament_pairing_algorithms/files/11525334/Sun_May_21_14_54_10_2023_B_round_14_based_on_12.log)

**Comment by spherulitic** [comment]
Note -- this was the first round paired after a round robin, so every possible pairing was one repeat.

**Comment by jvc56** [comment]
This is a bug, it should consider back-to-back repeats undesirable. I will investigate this issue.

**Comment by jvc56** [comment]
Actually, never mind. This is WAD. Back-to-back repeats will only be penalized if both players have absolutely no chance of cashing:

Lowest ranked possible winner for rank 1: 9   (#6)   Rackham, Anita          6.0  +145 
Lowest ranked possible winner for rank 2: 11  (#10)  Collins, Betzy          4.0  -181 
Lowest ranked possible winner for rank 3: 11  (#10)  Collins, Betzy          4.0  -181 
Lowest ranked possible winner for rank 4: 13  (#11)  Aitken, Terry           3.0  -547

**Comment by spherulitic** [comment]
It looks like this really is an edge case. In round 14/22, in a division of 14, following a Round Robin, one of the bottom four had a small chance of cashing, leaving the bottom two to coincidentally have back-to-back pairings. In this particular case we don't want the back-to-back, but if the same situation happening in round 19/22, say, the pairings in contention should outweigh the back-to-back. Still considering how to define this in the form of a requirement.
